# Generated by Django 3.2.9 on 2021-11-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='exp_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
